In [3]:
import pandas as pd
import os

data = pd.DataFrame({
    "Name": ["John Doe", "Jane Smith", "Emily Davis", "Michael Brown"],
    "Age": [28, 34, 41, 37],
    "Occupation": ["Software Engineer", "Data Scientist", "Product Manager", "UX Designer"]
})

data

            Name  Age         Occupation
0       John Doe   28  Software Engineer
1     Jane Smith   34     Data Scientist
2    Emily Davis   41    Product Manager
3  Michael Brown   37        UX Designer

# CSV

In [4]:
# Convert to csv
data.to_csv("emp.csv", index=False)

In [28]:
# Read data and display it
df = pd.read_csv("emp.csv")
df

            Name  Age         Occupation
0       John Doe   28  Software Engineer
1     Jane Smith   34     Data Scientist
2    Emily Davis   41    Product Manager
3  Michael Brown   37        UX Designer

In [32]:
# Display name and age
print("Age :- ", df["Age"].to_list())
print("Name :- ", df["Name"].to_list())

Age :-  [28, 34, 41, 37]
Name :-  ['John Doe', 'Jane Smith', 'Emily Davis', 'Michael Brown']

In [33]:
# Calculate avg age
df["Age"].mean()

np.float64(35.0)

In [53]:
# File size
print("CSV size:", os.path.getsize("emp.csv"))

CSV size: 139

# JSON

In [8]:
# Convert to JSON
data.to_json("emp.json", orient="records", indent=4)

In [34]:
# Read data and display it
df = pd.read_json("emp.json")
df

            Name  Age         Occupation
0       John Doe   28  Software Engineer
1     Jane Smith   34     Data Scientist
2    Emily Davis   41    Product Manager
3  Michael Brown   37        UX Designer

In [35]:
# Display name and age
print("Age :- ", df["Age"].to_list())
print("Name :- ", df["Name"].to_list())

Age :-  [28, 34, 41, 37]
Name :-  ['John Doe', 'Jane Smith', 'Emily Davis', 'Michael Brown']

In [36]:
# Calculate avg age
df["Age"].mean()

np.float64(35.0)

In [54]:
# File size
print("JSON size:", os.path.getsize("emp.json"))

JSON size: 397

# XML

In [10]:
# Convert to XML
data.to_xml("emp.xml", root_name="employees", row_name="employee", index=False)

In [45]:
# Read data and display it
df = pd.read_xml("emp.xml")
df

            Name  Age         Occupation
0       John Doe   28  Software Engineer
1     Jane Smith   34     Data Scientist
2    Emily Davis   41    Product Manager
3  Michael Brown   37        UX Designer

In [38]:
# Display name and age
print("Age :- ", df["Age"].to_list())
print("Name :- ", df["Name"].to_list())

Age :-  [28, 34, 41, 37]
Name :-  ['John Doe', 'Jane Smith', 'Emily Davis', 'Michael Brown']

In [46]:
# Calculate avg age
df["Age"].mean()

np.float64(35.0)

In [55]:
# File size
print("XML size:", os.path.getsize("emp.xml"))

XML size: 535

# HDF5

In [ ]:
!pip install tables

In [13]:
# Convert to hdf5
data.to_hdf("emp.h5", key="employees", mode="w")

In [47]:
# Read data and display it
df = pd.read_hdf("emp.h5", key="employees")
df

            Name  Age         Occupation
0       John Doe   28  Software Engineer
1     Jane Smith   34     Data Scientist
2    Emily Davis   41    Product Manager
3  Michael Brown   37        UX Designer

In [40]:
# Display name and age
print("Age :- ", df["Age"].to_list())
print("Name :- ", df["Name"].to_list())

Age :-  [28, 34, 41, 37]
Name :-  ['John Doe', 'Jane Smith', 'Emily Davis', 'Michael Brown']

In [48]:
# Calculate avg age
df["Age"].mean()

np.float64(35.0)

In [56]:
# File size
print("HDF5 size:", os.path.getsize("emp.h5"))

HDF5 size: 1064184

# Parquet

In [14]:
!pip install pyarrow

Requirement already satisfied: pyarrow in /usr/local/lib/python3.12/dist-packages (18.1.0)

In [16]:
# Convert of parquet
data.to_parquet("emp.parquet", engine="pyarrow")

In [49]:
# Read data and display it
df = pd.read_parquet("emp.parquet", engine="pyarrow")
df

            Name  Age         Occupation
0       John Doe   28  Software Engineer
1     Jane Smith   34     Data Scientist
2    Emily Davis   41    Product Manager
3  Michael Brown   37        UX Designer

In [42]:
# Display name and age
print("Age :- ", df["Age"].to_list())
print("Name :- ", df["Name"].to_list())

Age :-  [28, 34, 41, 37]
Name :-  ['John Doe', 'Jane Smith', 'Emily Davis', 'Michael Brown']

In [50]:
# Calculate avg age
df["Age"].mean()

np.float64(35.0)

In [57]:
# File size
print("Parquet size:", os.path.getsize("emp.parquet"))

Parquet size: 2747

# AVRO

In [19]:
!pip install fastavro

Requirement already satisfied: fastavro in /usr/local/lib/python3.12/dist-packages (1.12.1)

In [20]:
# Convert to avro
from fastavro import writer, parse_schema

# Specify schema
schema = {
    "doc": "Employee data",
    "name": "Employee",
    "namespace": "example",
    "type": "record",
    "fields": [
        {"name": "Name", "type": "string"},
        {"name": "Age", "type": "int"},
        {"name": "Occupation", "type": "string"}
    ]
}

# Convert dataframe to list of records
records = data.to_dict(orient="records")

# Parse schema
parsed_schema = parse_schema(schema)

# Write to avro file
with open("emp.avro", "wb") as out:
    writer(out, parsed_schema, records)

In [51]:
# Read data and display it
from fastavro import reader

with open("emp.avro", "rb") as f:
  df = pd.DataFrame(reader(f))

df

            Name  Age         Occupation
0       John Doe   28  Software Engineer
1     Jane Smith   34     Data Scientist
2    Emily Davis   41    Product Manager
3  Michael Brown   37        UX Designer

In [44]:
# Display name and age
print("Age :- ", df["Age"].to_list())
print("Name :- ", df["Name"].to_list())

Age :-  [28, 34, 41, 37]
Name :-  ['John Doe', 'Jane Smith', 'Emily Davis', 'Michael Brown']

In [52]:
# Calculate avg age
df["Age"].mean()

np.float64(35.0)

In [58]:
# File size
print("AVRO size:", os.path.getsize("emp.avro"))

AVRO size: 374