# Loading dataset and preprocessing

In [1]:
import pandas as pd
df = pd.read_csv("Emotion_classify_Data.csv")
df.head(5)

                                             Comment Emotion
0  i seriously hate one subject to death but now ...    fear
1                 im so full of life i feel appalled   anger
2  i sit here to write i start to dig out my feel...    fear
3  ive been really angry with r and i feel like a...     joy
4  i feel suspicious if there is no one outside l...    fear

In [2]:
df['Emotion'].value_counts()

Emotion
anger    2000
joy      2000
fear     1937
Name: count, dtype: int64

In [3]:
# Mapping target column
df['Emotion_num'] = df['Emotion'].map({
    'anger' : 0,
    'joy': 1,
    'fear': 2,
})

df.head(5)

                                             Comment Emotion  Emotion_num
0  i seriously hate one subject to death but now ...    fear            2
1                 im so full of life i feel appalled   anger            0
2  i sit here to write i start to dig out my feel...    fear            2
3  ive been really angry with r and i feel like a...     joy            1
4  i feel suspicious if there is no one outside l...    fear            2

In [4]:
# Preprocess function
import spacy
nlp = spacy.load("en_core_web_sm", disable=["parser", "tagger", "ner"])

def preprocess(texts):
    results = []
    for doc in nlp.pipe(texts, batch_size=1000):
        tokens = [token.lemma_ for token in doc if not token.is_stop and not token.is_punct]
        results.append(" ".join(tokens))
    return results

In [5]:
df["Comment"] = preprocess(df["Comment"])

/usr/local/lib/python3.12/dist-packages/spacy/pipeline/lemmatizer.py:188: UserWarning: [W108] The rule-based lemmatizer did not find POS annotation for one or more tokens. Check that your pipeline includes components that assign token.pos, typically 'tagger'+'attribute_ruler' or 'morphologizer'.
  warnings.warn(Warnings.W108)

In [6]:
df.head()

                                             Comment Emotion  Emotion_num
0   seriously hate subject death feel reluctant drop    fear            2
1                               m life feel appalled   anger            0
2  sit write start dig feelings think afraid acce...    fear            2
3          ve angry r feel like idiot trusting place     joy            1
4      feel suspicious outside like rapture happened    fear            2

In [ ]:
# Train test split
from sklearn.model_selection import train_test_split
X = df['Comment']
Y = df['Emotion_num']

X_train, X_test, Y_train, Y_test = train_test_split(X, Y, test_size=0.2, stratify=df['Emotion_num'])

# Applying BoW and Naive Bayes, Random forest

In [ ]:
from sklearn.pipeline import Pipeline
from sklearn.feature_extraction.text import CountVectorizer
from sklearn.naive_bayes import MultinomialNB

clf = Pipeline([
    ('vectorizer', CountVectorizer()),
    ('nb', MultinomialNB())
])

clf.fit(X_train, Y_train)
clf.score(X_test, Y_test)

0.914983164983165

In [ ]:
from sklearn.metrics import classification_report
y_pred = clf.predict(X_test)
print(classification_report(Y_test, y_pred))

              precision    recall  f1-score   support

           0       0.90      0.92      0.91       400
           1       0.94      0.90      0.92       400
           2       0.90      0.93      0.91       388

    accuracy                           0.91      1188
   macro avg       0.92      0.92      0.92      1188
weighted avg       0.92      0.91      0.92      1188

In [ ]:
from sklearn.ensemble import RandomForestClassifier
clf = Pipeline([
    ('vectorizer', CountVectorizer()),
    ('rf', RandomForestClassifier())
])

clf.fit(X_train, Y_train)
clf.score(X_test, Y_test)

0.946969696969697

In [ ]:
y_pred = clf.predict(X_test)
print(classification_report(Y_test, y_pred))

              precision    recall  f1-score   support

           0       0.92      0.97      0.94       400
           1       0.97      0.95      0.96       400
           2       0.95      0.93      0.94       388

    accuracy                           0.95      1188
   macro avg       0.95      0.95      0.95      1188
weighted avg       0.95      0.95      0.95      1188

# Applying n-grams and Naive Bayes, Random forest

In [ ]:
clf = Pipeline([
    ('vectorizer', CountVectorizer(ngram_range=(2,2))),
    ('nb', MultinomialNB())
])

clf.fit(X_train, Y_train)
clf.score(X_test, Y_test)

0.7676767676767676

In [ ]:
y_pred = clf.predict(X_test)
print(classification_report(Y_test, y_pred))

              precision    recall  f1-score   support

           0       0.69      0.83      0.76       400
           1       0.81      0.68      0.74       400
           2       0.83      0.79      0.81       388

    accuracy                           0.77      1188
   macro avg       0.78      0.77      0.77      1188
weighted avg       0.78      0.77      0.77      1188

In [ ]:
clf = Pipeline([
    ('vectorizer', CountVectorizer(ngram_range=(2,2))),
    ('rf', RandomForestClassifier())
])

clf.fit(X_train, Y_train)
clf.score(X_test, Y_test)

0.7188552188552189

In [ ]:
y_pred = clf.predict(X_test)
print(classification_report(Y_test, y_pred))

              precision    recall  f1-score   support

           0       0.60      0.83      0.70       400
           1       0.74      0.65      0.69       400
           2       0.93      0.67      0.78       388

    accuracy                           0.72      1188
   macro avg       0.76      0.72      0.72      1188
weighted avg       0.75      0.72      0.72      1188

# Applying TF-IDF and Naive Bayes, Random forest

In [ ]:
from sklearn.feature_extraction.text import TfidfVectorizer
clf = Pipeline([
    ('vectorizer', TfidfVectorizer()),
    ('nb', MultinomialNB())
])

clf.fit(X_train, Y_train)
clf.score(X_test, Y_test)

0.9225589225589226

In [ ]:
y_pred = clf.predict(X_test)
print(classification_report(Y_test, y_pred))

              precision    recall  f1-score   support

           0       0.91      0.92      0.92       400
           1       0.94      0.93      0.93       400
           2       0.91      0.92      0.92       388

    accuracy                           0.92      1188
   macro avg       0.92      0.92      0.92      1188
weighted avg       0.92      0.92      0.92      1188

In [ ]:
clf = Pipeline([
    ('vectorizer', TfidfVectorizer()),
    ('rf', RandomForestClassifier())
])

clf.fit(X_train, Y_train)
clf.score(X_test, Y_test)

0.9402356902356902

In [ ]:
y_pred = clf.predict(X_test)
print(classification_report(Y_test, y_pred))

              precision    recall  f1-score   support

           0       0.94      0.94      0.94       400
           1       0.93      0.94      0.94       400
           2       0.95      0.94      0.94       388

    accuracy                           0.94      1188
   macro avg       0.94      0.94      0.94      1188
weighted avg       0.94      0.94      0.94      1188

### Making predictions

In [ ]:
df["Comment"][0]

'seriously hate subject death feel reluctant drop'

In [ ]:
clf.predict([df["Comment"][0]])

array([2])

In [ ]:
clf.predict(["I am so happy"])

array([1])

# Using fasttext vectors

In [7]:
df['label'] = '__label__' + df['Emotion'].astype(str)
df.head()

,Comment,Emotion,Emotion_num,label
0,seriously hate subject death feel reluctant drop,fear,2,__label__fear
1,m life feel appalled,anger,0,__label__anger
2,sit write start dig feelings think afraid acce...,fear,2,__label__fear
3,ve angry r feel like idiot trusting place,joy,1,__label__joy
4,feel suspicious outside like rapture happened,fear,2,__label__fear

In [8]:
# Combining label and comment
df['label_comment'] = df['label'] + ' ' + df['Comment']
df.head(3)

,Comment,Emotion,Emotion_num,label,label_comment
0,seriously hate subject death feel reluctant drop,fear,2,__label__fear,__label__fear seriously hate subject death fee...
1,m life feel appalled,anger,0,__label__anger,__label__anger m life feel appalled
2,sit write start dig feelings think afraid acce...,fear,2,__label__fear,__label__fear sit write start dig feelings thi...

In [9]:
# Train test split
from sklearn.model_selection import train_test_split
df = df[['label_comment']]

train, test = train_test_split(df, test_size=0.2)

In [10]:
train.to_csv("emotion.train", columns=["label_comment"], index=False, header=False)
test.to_csv("emotion.test", columns=["label_comment"], index=False, header=False)

In [12]:
!pip install fasttext

Requirement already satisfied: fasttext in /usr/local/lib/python3.12/dist-packages (0.9.3)
Requirement already satisfied: pybind11>=2.2 in /usr/local/lib/python3.12/dist-packages (from fasttext) (3.0.1)
Requirement already satisfied: setuptools>=0.7.0 in /usr/local/lib/python3.12/dist-packages (from fasttext) (75.2.0)
Requirement already satisfied: numpy in /usr/local/lib/python3.12/dist-packages (from fasttext) (2.0.2)

In [15]:
import fasttext

model = fasttext.train_supervised(input="emotion.train")
model.test("emotion.test")

(1188, 0.9486531986531986, 0.9486531986531986)

### Making predictions

In [17]:
model.predict(["I am happy"])

([['__label__joy']], [array([0.95442456], dtype=float32)])

In [20]:
model.predict(["I very scared"])

([['__label__fear']], [array([1.000007], dtype=float32)])

In [19]:
model.predict(["Whats wrong with you?"])

([['__label__anger']], [array([0.7320183], dtype=float32)])