# Remove stopwords from text

In [4]:
import spacy
from spacy.lang.en.stop_words import STOP_WORDS
print(STOP_WORDS)

{'before', 'nowhere', '’d', 'side', 'bottom', 'take', 'various', 'some', 'cannot', 'every', 'each', 'among', 'and', 'nothing', 'more', 'seem', 'get', 'wherein', 'back', 'since', 'two', 'whom', 'was', 'thence', 're', 'via', 'must', 'never', 'very', 'hence', 'name', 'had', 'afterwards', 'should', 'together', 'four', 'fifty', 'beforehand', 'no', 'just', 'we', 'thru', 'quite', 'seeming', 'using', 'me', 'well', 'during', 'hers', 'ours', 'ten', 'do', 'enough', 'therein', 'those', 'may', 'whoever', 'anyway', 'either', 'between', 'over', 'your', '’s', 'for', 'elsewhere', 'whereby', 'only', 'yours', 'also', 'call', 'became', 'somewhere', 'same', '’ve', 'used', 'formerly', 'although', 'has', 'neither', 'whereupon', 'are', 'give', 'my', 'always', 'eight', 'this', 'out', 'hundred', '‘ve', '‘ll', 'until', 'herein', 'within', 'not', 'whence', 'whereafter', '‘d', 'would', 'often', 'around', 'down', 'too', 'unless', '‘re', 'therefore', 'now', 'however', 'nine', 'else', 'others', 'former', 'thereafter', 'onto', 'one', 'everything', 'hereby', 'themselves', 'them', 'least', 'move', 'himself', 'have', 'yet', 'twenty', 'ca', 'already', 'fifteen', 'above', 'even', '’re', 'be', 'though', 'see', 'six', 'part', 'forty', "'re", 'once', 'at', 'sometime', 'meanwhile', 'beyond', 'few', 'a', 'he', 'put', 'everyone', 'towards', 'moreover', 'that', 'another', 'off', 'up', 'any', 'could', 'were', 'along', 'yourself', 'n‘t', 'amount', 'when', 'almost', 'against', 'indeed', 'nobody', 'does', 'front', 'doing', 'whose', '‘s', 'whereas', 'into', 'less', 'after', 'third', 'all', 'if', 'i', 'show', 'him', 'please', 'thereby', 'their', 'again', 'his', 'been', 'someone', 'might', 'why', 'but', 'to', 'somehow', 'through', "'ve", 'about', 'noone', 'such', 'will', "'ll", 'done', 'own', 'latter', 'five', 'thereupon', 'by', "'m", 'much', 'under', 'nevertheless', 'top', 'empty', 'seems', 'none', 'per', 'what', 'mine', 'while', 'whenever', 'three', '‘m', 'yourselves', 'whether', 'ever', '’ll', 'hereupon', 'n’t', 'can', 'an', 'anything', 'how', 'thus', 'below', 'anyhow', 'next', 'as', 'regarding', 'first', 'from', 'or', 'otherwise', 'mostly', 'further', 'really', 'beside', 'go', 'become', 'its', 'made', '’m', 'the', 'where', 'say', 'being', 'they', 'these', 'both', 'keep', 'upon', "n't", 'then', 'due', 'without', "'d", 'myself', 'still', 'on', 'itself', 'you', "'s", 'across', 'whither', 'whatever', 'nor', 'there', 'than', 'alone', 'anyone', 'behind', 'except', 'last', 'many', 'several', 'it', 'her', 'serious', 'perhaps', 'sometimes', 'other', 'toward', 'amongst', 'rather', 'something', 'in', 'of', 'everywhere', 'us', 'did', 'who', 'eleven', 'whole', 'am', 'twelve', 'is', 'wherever', 'latterly', 'seemed', 'herself', 'so', 'she', 'hereafter', 'throughout', 'which', 'anywhere', 'our', 'make', 'ourselves', 'with', 'becoming', 'full', 'namely', 'becomes', 'sixty', 'because', 'here', 'most', 'besides'}

In [7]:
nlp = spacy.load("en_core_web_sm")
doc = nlp("We just opened our wings, the flying part is coming soon")
no_stop_words = []

for token in doc:
  if not token.is_stop:
    no_stop_words.append(token.text)

print(" ".join(no_stop_words))

opened wings , flying coming soon

In [8]:
# Remove stopwords function
def preprocess(text):
  doc = nlp(text)
  no_stop_words = [token.text for token in doc if not token.is_stop]
  return " ".join(no_stop_words)

In [9]:
preprocess("Musk wants time to prepare for a trial over his")

'Musk wants time prepare trial'

In [10]:
preprocess("The other is not other but your divine brother")

'divine brother'

# Remove stopwords from dataframe

In [14]:
import pandas as pd
import json

data = []
with open("doj_press.json", "r") as f:
    for line in f:
        try:
            data.append(json.loads(line))
        except json.JSONDecodeError as e:
            print(f"Skipping malformed JSON line: {line.strip()}. Error: {e}")

df = pd.DataFrame(data)
df.head()

Skipping malformed JSON line: {"id": "12-366", "title": "Former East Alton, Ill., Police Sergeant Pleads Guilty to Abusing an Arrestee", "contents": "WASHINGTON \u2013 Brent E. Wells, a former police sergeant with the East Alton, Ill., Police Department, pleaded guilty yesterday in U.S. District Court in East St. Louis, Ill., to violating the civil rights of a civilian by assaulting the man during an arrest in front of Wells\u2019s home on Sept. 11, 2010, the Justice Department announced. \u00a0 Yesterday in court, before U.S. Magistrate Court Judge Donald G. Wilk. Error: Unterminated string starting at: line 1 column 120 (char 119)

,id,title,contents,date,topics,components
0,None,Convicted Bomb Plotter Sentenced to 30 Years,"PORTLAND, Oregon. – Mohamed Osman Mohamud, 23,...",2014-10-01T00:00:00-04:00,[],[National Security Division (NSD)]
1,12-919,$1 Million in Restitution Payments Announced t...,WASHINGTON – North Carolina’s Waccamaw River...,2012-07-25T00:00:00-04:00,[],[Environment and Natural Resources Division]
2,11-1002,$1 Million Settlement Reached for Natural Reso...,BOSTON– A $1-million settlement has been...,2011-08-03T00:00:00-04:00,[],[Environment and Natural Resources Division]
3,10-015,10 Las Vegas Men Indicted \r\nfor Falsifying V...,WASHINGTON—A federal grand jury in Las Vegas...,2010-01-08T00:00:00-05:00,[],[Environment and Natural Resources Division]
4,18-898,$100 Million Settlement Will Speed Cleanup Wor...,"The U.S. Department of Justice, the U.S. Envir...",2018-07-09T00:00:00-04:00,[Environment],[Environment and Natural Resources Division]

In [16]:
# Filter out those rows that do not have any topics associated with the case
df = df[df["topics"].str.len()!=0]
df.head()

,id,title,contents,date,topics,components
4,18-898,$100 Million Settlement Will Speed Cleanup Wor...,"The U.S. Department of Justice, the U.S. Envir...",2018-07-09T00:00:00-04:00,[Environment],[Environment and Natural Resources Division]
7,14-1412,14 Indicted in Connection with New England Com...,A 131-count criminal indictment was unsealed t...,2014-12-17T00:00:00-05:00,[Consumer Protection],[Civil Division]
19,17-1419,2017 Southeast Regional Animal Cruelty Prosecu...,The United States Attorney’s Office for the Mi...,2017-12-14T00:00:00-05:00,[Environment],"[Environment and Natural Resources Division, U..."
22,15-1562,21st Century Oncology to Pay $19.75 Million to...,"21st Century Oncology LLC, has agreed to pay $...",2015-12-18T00:00:00-05:00,"[False Claims Act, Health Care Fraud]",[Civil Division]
23,17-1404,21st Century Oncology to Pay $26 Million to Se...,21st Century Oncology Inc. and certain of its ...,2017-12-12T00:00:00-05:00,"[Health Care Fraud, False Claims Act]","[Civil Division, USAO - Florida, Middle]"

In [18]:
# Remove stopwords
df = df.head(100)
df["contents_new"] = df.contents.apply(preprocess)
df.head()

,id,title,contents,date,topics,components,contents_new
4,18-898,$100 Million Settlement Will Speed Cleanup Wor...,"The U.S. Department of Justice, the U.S. Envir...",2018-07-09T00:00:00-04:00,[Environment],[Environment and Natural Resources Division],"U.S. Department Justice , U.S. Environmental P..."
7,14-1412,14 Indicted in Connection with New England Com...,A 131-count criminal indictment was unsealed t...,2014-12-17T00:00:00-05:00,[Consumer Protection],[Civil Division],131 - count criminal indictment unsealed today...
19,17-1419,2017 Southeast Regional Animal Cruelty Prosecu...,The United States Attorney’s Office for the Mi...,2017-12-14T00:00:00-05:00,[Environment],"[Environment and Natural Resources Division, U...",United States Attorney Office Middle District ...
22,15-1562,21st Century Oncology to Pay $19.75 Million to...,"21st Century Oncology LLC, has agreed to pay $...",2015-12-18T00:00:00-05:00,"[False Claims Act, Health Care Fraud]",[Civil Division],"21st Century Oncology LLC , agreed pay $ 19.75..."
23,17-1404,21st Century Oncology to Pay $26 Million to Se...,21st Century Oncology Inc. and certain of its ...,2017-12-12T00:00:00-05:00,"[Health Care Fraud, False Claims Act]","[Civil Division, USAO - Florida, Middle]",21st Century Oncology Inc. certain subsidiarie...

# Find % of stop words compared to total words

In [21]:
text = '''
Thor: Love and Thunder is a 2022 American superhero film based on Marvel Comics featuring the character Thor, produced by Marvel Studios and
distributed by Walt Disney Studios Motion Pictures. It is the sequel to Thor: Ragnarok (2017) and the 29th film in the Marvel Cinematic Universe (MCU).
The film is directed by Taika Waititi, who co-wrote the script with Jennifer Kaytin Robinson, and stars Chris Hemsworth as Thor alongside Christian Bale, Tessa Thompson,
Jaimie Alexander, Waititi, Russell Crowe, and Natalie Portman. In the film, Thor attempts to find inner peace, but must return to action and recruit Valkyrie (Thompson),
Korg (Waititi), and Jane Foster (Portman)—who is now the Mighty Thor—to stop Gorr the God Butcher (Bale) from eliminating all gods.
'''
doc = nlp(text)

stopwords = []
not_stopwords = []

for token in doc:
  if token.is_stop:
    stopwords.append(token)
  else:
    not_stopwords.append(token)

print("Total words:", len(doc))
print("Total stopwords:", len(stopwords))
print("Total not stopwords:", len(not_stopwords))
print("% of stopwords", len(stopwords)/len(doc)*100)

Total words: 160
Total stopwords: 40
Total not stopwords: 120
% of stopwords 25.0

# Remove a stopword from predefined stopwords set

In [22]:
# Removing stopwords in the below example, changes the sentiment of 2nd text
print(preprocess("this is a good movie"))
print(preprocess("this is not a good movie"))

good movie
good movie

In [24]:
# Remove "not" stopword from stopwords set
stop_words_set = set(STOP_WORDS)
stop_words_set.remove("not")
nlp.vocab["not"].is_stop = False

In [25]:
print(preprocess("this is a good movie"))
print(preprocess("this is not a good movie"))

good movie
not good movie

# Output the most frequently used word

In [30]:
text = ''' The India men's national cricket team, also known as Team India or the Men in Blue, represents India in men's international cricket.
It is governed by the Board of Control for Cricket in India (BCCI), and is a Full Member of the International Cricket Council (ICC) with Test,
One Day International (ODI) and Twenty20 International (T20I) status. Cricket was introduced to India by British sailors in the 18th century, and the
first cricket club was established in 1792. India's national cricket team played its first Test match on 25 June 1932 at Lord's, becoming the sixth team to be
granted test cricket status.
'''
doc = nlp(text)

remaning_tokens = [token.text for token in doc if not token.is_stop and not token.is_punct]
freq_word = {}

for token in remaning_tokens:
  if token != '\n' and token != ' ':
    if token not in freq_word:
      freq_word[token] = 1
    else:
      freq_word[token] +=1

max_freq = max(freq_word.values())
max_key = [key for key, value in freq_word.items() if value == max_freq]
print(max_key)

['India']